### ISSUE TITLE
Error in the name of the city from Edenred

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#13]
ENVIROMENT: production
COMPANY: Edenred
URL: [Edenred peviitor.ro](https://scrapers.peviitor.ro/src/edenred/)
Company's Career website: [Edenred official website](https://www.edenred.ro/ro/descopera-jobul-potrivit)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

1. Click on Firme from footer.
2. Enter Edenred in the search bar.
3. Click the button under the company's logo.
4. Click the Run Scraper button.

Expected result:

1. All jobs contain valid city names

Actual result:

2. Jobs do not contain valid city names
<img width="886" alt="bug edenred" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/acac279b-615f-496a-830c-2fb9ed333e06">

**Comment by cristiol** [comment]
fixed
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/6605dde1-6bb8-4cfa-9896-94d2f1c1e455)

**Comment by AdelinaGuliman** [comment]
Sfantu Gheorghe  still appears on my laptop in red
<img width="1086" alt="bug edenred 1 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/3052b299-a4f4-45a4-9f69-fe202524f8ae">

**Comment by cristiol** [comment]
If you press the 'run scraper' button, it will appear in green.

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/fbb714ae-f3d2-4289-9c4b-245828662eba)

**Comment by AdelinaGuliman** [comment]
Case closed!
